django_portfolio/urls.py
import statistics
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('weblog/',include('weblog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weblog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'weblog'

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail'),
]

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

# Create your models here.

class Project(models.Model):
    image = ImageField(upload_to='portfolio/images/')
    title_proj = CharField(max_length = 50)
    Description = CharField(max_length = 80)
    tags = CharField(max_length = 50)
    url_git = URLField(blank=True)

weblog/models.py
from django.db import models

import datetime
# Create your models here.

class Post(models.Model):
    image = models.ImageField(upload_to='weblog/images/')
    title_proj = models.CharField(max_length = 100)
    description = models.TextField()
    tags = models.CharField(max_length = 50)
    url_git = models.URLField(blank=True)
    date = models.DateField(datetime.date.today)

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.

def home(request):
    projects = Project.objects.all()
    return render (request, 'home.html', {'projects': projects})

weblog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# Create your views here.
def render_posts(request):
    posts = Post.objects.all()

    return render(request, 'posts.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render (request, 'post_detail.html', {'post':post})

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}
 <header class="row">
    <div class="col-md-4">
        <img src="{% static 'portfolio/bs.jpg' %}" >
    </div>
    <div class="col-md-8">
<h1> yo soy <strong>Yoselin</strong></h1>
<h3>Soy un desarrollador</h3>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione debitis laborum quasi obcaecati, illo, voluptatibus voluptate nisi nostrum consequatur molestiae aspernatur quo quia vitae doloribus, possimus praesentium voluptatum modi error vero. Fugiat dolor delectus non cumque, voluptates, sed repellendus ipsum ipsa commodi at dignissimos exercitationem! Repellat magnam sequi accusamus id at eius. Et eaque soluta totam laboriosam saepe sunt, vitae eveniet vel beatae odit veritatis aspernatur quasi dolores adipisci voluptatem magnam magni iste? Quo aut eveniet, veniam debitis placeat nam sapiente soluta, ab deserunt, inventore dolor ea quaerat. Dignissimos, maxime harum doloribus sunt voluptatem neque tempora quasi aspernatur in corporis? </p>
<a href="{% static 'portfolio/cv.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3"> Download cv </a>


    </div>
 </header>


{% for project in projects %}
    <h2>{{project.title_proj}}</h2>
    <p>{{project.description}}</p>
    <img src="{{project.image.url}}" alt="{{project.title_proj}}">
    {% if project.url %}
        <a href="{{project.url}}">{{project.url_git}}</a>
    {% endif%}
{% endfor %}
{% endblock %}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portafolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    
    {% include 'partials/navbar.html' %}
    <div class='container p-4'>
    
    {% block content %}
    {% endblock %}
    </div>
    
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold fst-italic" href="/">PORTAFOLIO</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto" >
          <li class="nav-item">
            <a class="nav-link" href="{% url 'weblog:posts' %}">Weblog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="">Download cv</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

weblog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}

<h1>Post</h1>


    <h2 href="{{post.title_proj}}"></h2>
    <h3>{{post.date}}</h3>

    <p>{{post.description}}</p>
    <img src="{{post.image.url}}" alt="{{post.title_proj}}">

{% endblock %}

weblog/templates/posts.html
{% extends 'layout.html' %}
{% block content %}

<h1>post</h1>
{% for post in posts %}

    <h2 href="{{post.title_proj}}"></h2>
   
    <p>{{post.description|truncatechars:200}}</p>
    <p>{{ost.date|date:'M d Y'|upper}}</p>
    <img src="{{post.image.url}}" alt="{{post.title_proj}}">

    <a href="{% url 'weblog:post_detail' post.id %}">{{post.title_proj}}</a>


{% endfor %}
{% endblock %}